name: deploy news-api by ZUNO
on: [workflow_dispatch]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: supnobita/ssh-action@master
              with:
                  host: 54.169.185.39
                  username: ubuntu
                  key: ${{ secrets.NEWS_DEV_SECRET }}
                  port: 22
                  envs: GITHUB_RUN_NUMBER
                  script: |
                      cd code/
                      rm -rf news-api/
                      git clone https://${{ secrets.NEWS_DEV_TOKEN_SSH }}@github.com/zuno90/news-api.git
                      cd news-api/
                      DOCKER_BUILDKIT=1 docker build -t news-api:$GITHUB_RUN_NUMBER .
                      docker stop news-api || echo "OK"
                      docker rm news-api || echo "OK"
                      docker run -d --name news-api -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
                          -e NODE_ENV=production \
                          -e HOST=172.31.16.179 \
                          -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
                          -e MONGO_PORT=${{ secrets.MONGO_PORT }} \
                          -e MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
                          -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                          -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
                          -e SECRET=${{ secrets.SECRET }} \
                          -e GG_DRIVE_CLIENT=${{ secrets.GG_DRIVE_CLIENT }} \
                          -e GG_DRIVE_SECRET=${{ secrets.GG_DRIVE_SECRET }} \
                          -e GG_DRIVE_REDIRECT_URI=${{ secrets.GG_DRIVE_REDIRECT_URI }} \
                          -e GG_DRIVE_REFRESH_TOKEN=${{ secrets.GG_DRIVE_REFRESH_TOKEN }} \
                          news-api:$GITHUB_RUN_NUMBER
